//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHackathon_Waste
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBin
    {
        public int ID { get; set; }
        public double latitute { get; set; }
        public double longitude { get; set; }
        public string description { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
